application: oohembed
version: vanilla
runtime: python
api_version: 1

default_expiration: "15d"

handlers:
- url: /dumble/
  static_files: dumble/index.html
  upload: dumble/index.html

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /crossdomain.xml
  static_files: static/crossdomain.xml
  upload: static/crossdomain.xml

- url: /endpoints.json
  static_files: static/endpoints.json
  upload: static/endpoints.json
  mime_type: application/json

- url: /dumble
  static_dir: dumble

- url: /static
  static_dir: static

- url: /admin/.*
  script: main.py
  login: admin

- url: /.*
  script: main.py
